all: floyd cycle dijkstra bfs knight1 island2 rootdist polycarp floors
floyd: floyd.cpp
	g++ $^ -o $@
cycle: cycle.cpp
	g++ -g -std=c++11 $^ -o $@
dijkstra: dijkstra.cpp
	g++ -g -std=c++11 $^ -o $@
bfs: bfs.cpp
	g++ -g -std=c++11 $^ -o $@
knight1: knight1.cpp
	g++ -g -std=c++11 $^ -o $@
island2: island2.cpp
	g++ -g -std=c++11 $^ -o $@
rootdist: rootdist.cpp
	g++ -g -std=c++11 $^ -o $@
polycarp: polycarp.cpp
	g++ -g -std=c++11 $^ -o $@
floors: floors.cpp
	g++ -g -std=c++11 $^ -o $@
